<?php
Am_Di::getInstance()->plugins_protect->get('wordpress')->startLayout($this, $title,true);
get_header();
?>
<div id="main-content" class="main-content">
	<div id="primary" class="content-area">
		<div id="content" class="site-content" role="main">
<div style="padding:1em;">
<?php 
include dirname(__FILE__)."/../amember.php";
?>
</div>		
</div><!-- #content -->
	</div><!-- #primary -->
	<?php get_sidebar( 'content' ); ?>
</div><!-- #main-content -->

<?php
get_sidebar();
get_footer();
