<div class="grid-container">
<table class="grid">
<tr>
    <th><?php __e('Date/Time') ?></th>
    <th><?php __e('Referer') ?></th>
</tr>
<?php 
foreach ($clicks as $c): 
    printf("<tr><td>%s</td>
            <td><a href='%s' target='blank'>%s</a></td>
            </tr>\n",
            amDateTime($c->time),
            $this->escape($c->referer), $this->escape($c->referer)
            );
endforeach;
?>
</table>
</div>
