<div class="am-login-form-wrapper">
    <?php echo $this->blocks('login/form/before') ?>
    <div class="am-form am-login-form" style="width:350px; margin: 0 auto">
        <form name="login" method="post" <?php if ($form_action) echo "action='$form_action'"; ?>>
            <fieldset>
                <legend><?php __e('Member Login') ?></legend>
                <div class="row" id="recaptcha-row" style="<?php if (empty($recaptcha)): ?>display: none;<?php endif?>" data-recaptcha-theme="<?php echo Am_Di::getInstance()->config->get('login_recaptcha_theme','red');?>">
                    <div class="element-title" style="display:none;"></div>
                    <div class="element am-element-recaptcha" id="recaptcha-element">
                        <?php echo @$recaptcha ?>
                    </div>
                </div>
                <div class="row">
                    <div class="element-title">
                        <label class="element-title" for="login"><?php __e('E-Mail Address or Username') ?></label>
                    </div>
                    <div class="element">
                        <input type="text" id="login" name="amember_login" size="15" value="<?php p(@$_REQUEST['amember_login']) ?>" autofocus="autofocus"  placeholder="<?php __e('Email or Username') ?>" />
                    </div>
                </div>
                <div class="row">
                    <div class="element-title">
                        <label class="element-title" for="pass"><?php __e('Password') ?></label>
                    </div>
                    <div class="element">
                        <input type="password" id="pass" name="amember_pass" size="15" placeholder="<?php __e('Password') ?>" />
                    </div>
                </div>
                <?php if (@$this_config['remember_login'] && !@$this_config['remember_auto']): ?>
                <div class="row">
                    <div class="element-title">
                        <label class="element-title" for="remember"><?php __e('Remember my password?') ?></label>
                    </div>
                    <div class="element">
                        <input type="checkbox" name="remember_login" value="1"<?php if (@$_REQUEST['remember_login']): ?>checked="checked"<?php endif ?>>
                    </div>
                </div>
                <?php endif ?>
                <div class="row">
                    <div class="element">
                        <input type="submit" value="<?php __e('Login') ?>" />
                        <a href="javascript:;" class="local-link am-form-login-switch"><?php __e('Forgot password?') ?></a>
                    </div>
                </div>
            </fieldset>
            <?php echo Am_Controller::renderArrayAsInputHiddens($hidden) ?>
        </form>
    </div>
    <?php echo $this->blocks('login/form/after') ?>
</div>
<div class="am-sendpass-form-wrapper">
    <div class="am-form am-sendpass-form">
        <form name="sendpass" method="post" action="<?php echo REL_ROOT_URL ?>/sendpass">
            <fieldset>
                <legend><?php __e('Lost password') ?>?</legend>
                <div class="row">
                    <div class="element-title">
                        <label for="sendpass"><?php __e('Enter your E-Mail Address or Username') ?></label>
                    </div>
                    <div class="element"><input type="text" name="login" id="sendpass" size="15" placeholder="<?php __e('Email or Username') ?>" /></div>
                </div>
                <div class="row">
                    <div class="element">
                        <input type="submit" value="<?php __e('Get Password') ?>" />
                        <a href="javascript:;" class="local-link am-form-login-switch"><?php __e('I have password') ?></a>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
<script type="text/javascript">
jQuery('.am-form-login-switch').click(function(){
    jQuery('.am-login-form-wrapper, .am-sendpass-form-wrapper').toggle();
    jQuery('.am-login-form-wrapper .errors, .am-sendpass-form-wrapper .errors').remove();
})
</script>