<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title><?php p(isset($meta_title) ? $meta_title : $title) ?></title>
        <?php /*$this->printLayoutHead();*/ ?>
        <link type="text/css" rel="stylesheet" media="screen" href="/amember/application/default/views/public/css/bootstrap/css/bootstrap.css">
        <link type="text/css" rel="stylesheet" media="screen" href="/amember/application/default/views/public/css/style.css">
    </head>
    <body>
        <?php echo $this->placeholder('body-start'); ?>
        <div role="document" class="wrap container-fluid">
            <a name="top"></a>
            <div class="content row">
                <main role="main" class="main">
                    <div class="container">
                        <div class="row ">
                            <form action="/amember/login" method="post">
                                <div class="col-sm-7"></div>
                                <div class="col-sm-1">Username:</div>
                                <div class="col-sm-1"><input type="text" size="5" name="amember_login"></div>
                                <div class="col-sm-1">Password:</div>
                                <div class="col-sm-1"><input type="password" size="5" name="amember_pass"></div>
                                <div class="col-sm-1"><input type="submit" value="Login"></div>
                            </form>
                        </div>
                        
                        <div class="row"> 
                            <section class="menu_bg">
                                <nav class="menu_sec">
                                    <header role="banner" class="navbar navbar-inverse">
                                        <div class="container">
                                            <div class="navbar-header">
                                                <button data-target=".bs-navbar-collapse" data-toggle="collapse" type="button" class="navbar-toggle">
                                                    <span class="sr-only">Toggle navigation</span>
                                                    <span class="icon-bar"></span>  
                                                    <span class="icon-bar"></span>
                                                    <span class="icon-bar"></span>
                                                </button>
                                            </div>
                                            <nav role="navigation" class="collapse navbar-collapse bs-navbar-collapse">
                                                <ul class="nav navbar-nav">
                                                    <li><a href="#">OFFERS</a></li>            
                                                    <li><a href="#">NETWORKS</a></li>              
                                                    <li><a href="#">BIZOP</a></li>                
                                                    <li><a href="#">NEWSLETTER ARCHIVE</a></li>               
                                                    <li><a href="#">DAVE'SPICKS</a></li>              
                                                    <li><a href="#">ABOUT US</a></li>              
                                                </ul>
                                            </nav>
                                        </div>
                                    </header>
                                </nav>
                            </section>
                        </div>
                    </div>
                    <!-- end of menu_sec -->

                    <div class="body-cnt">
                        <?php include $this->_script('_content2.phtml'); ?>
                    </div>

                    <footer class="footer_sec">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="footer_sec_inner">
                                        <div class="footer_text"><p><a href="#">PRIVACY POLICY</a>&nbsp;&nbsp;&nbsp;<a href="#">TERM AND CONDITIONS</a>&nbsp;&nbsp;&nbsp;<a href="#">BLOG</a>&nbsp;&nbsp;&nbsp;Copyright McClain Concept Inc.</p></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </footer>


                </main>
            </div>
        </div>
        <?php echo $this->placeholder('body-finish'); ?>
    </body>
</html>