<div class="page-cnt">
<section class="signup">

	<div class="top-text">  Intro Text Here</div>
	<div class="row">
		<div class="col-sm-4">
			<div class="plan-box">
				<p class="main-title">free</p>
				<p class="price">$0</p>
				<p class="period">Per Month</p>

				<button type="button" class="btn btn-warning signup">Sign Up</button>

				<p class="item">Monthly E-Newsletter</p>
				<p class="item">Weekly Video Reviews</p>
				<p class="item">Exclusive Blog Content</p>

				<button type="button" class="btn btn-warning more">More Features</button>
			</div>
		</div>
		<div class="col-sm-4">
			<div class="plan-box">
				<p class="main-title">pro</p>
				<p class="price">$47</p>
				<p class="period">Per Month</p>

				<button type="button" class="btn btn-warning signup">Sign Up</button>

				<p class="item">all free membership content</p>
				<p class="item">Weekly network Reviews</p>
				<p class="item">Weekly mlm/biz op Reviews</p>
				<p class="item">monthly offer review webinars</p>
				<p class="item">Weekly top mobile offers</p>
				<p class="item">Weekly top desktop offers</p>
				<p class="item">Weekly top creative per offer</p>

				<button type="button" class="btn btn-warning more">More Features</button>
			</div>
		</div>
		<div class="col-sm-4">
			<div class="plan-box">
				<p class="main-title">platinum</p>
				<p class="price">$97</p>
				<p class="period">Per Month</p>

				<button type="button" class="btn btn-warning signup">Sign Up</button>

				<p class="item">all pro membership content</p>
				<p class="item">dave's weekly picks</p>
				<p class="item">search engine capabilities</p>
				<p class="item">Weekly campaign Reviews</p>
				<p class="item">newsletter archive</p>

				<button type="button" class="btn btn-warning more">More Features</button>
			</div>
		</div>
	</div>
</section>
</div>